# Generated by Django 5.0.3 on 2024-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamDwellProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Condo', 'Condo')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor', models.IntegerField()),
                ('parking_spots', models.IntegerField()),
                ('image', models.ImageField(upload_to='dreamdwell_property_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
