# Generated by Django 5.0.3 on 2024-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamdwell', '0002_client_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='move_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='property',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
